# Make sure not to name your pipeline deploy, as this will conflict with the built-in deploy action
name: deploy infra and app using github functions
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  NODE_VERSION: "18.x"
jobs:
  validate-credentials:
    name: validate azure credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      # generate credentials using this command, then store them in GitHub secrets
      # az ad sp create-for-rbac --name "pipelineCredentials" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group}

      - name: logout
        run: |
          az logout

  build-infrastructure:
    name: build infrastructure
    needs: validate-credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: build infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: "StirTrekAuto1"
          deploymentMode: incremental
          template: ./infra/main.bicep
          parameters: ./infra/main.parameters.json

  build-front-end:
    name: build react app
    needs: build-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Use node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install and build
        run: |
          cd frontEnd 
          cd my-react-app
          npm install
          npm run build

      - name: upload build artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: frontend-app
          path: "frontEnd/my-react-app/dist"
          if-no-files-found: error
          retention-days: 30

  deploy-front-end:
    name: deploy react app
    needs: build-front-end
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: downloading artifact
        uses: actions/download-artifact@v2

      - name: deploy to azure web app
        id: deploy-to-web-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: StirTrekTestFrontEnd
          package: ./frontend-app

  build-and-deploy-back-end:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    needs: deploy-front-end
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh # For Linux, use bash
        run: |
          pushd './backEnd'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: DrakeStirTrekApi
          package: "backEnd/output"
